services:
  app:
    build: .
    volumes:
      - .:/app
      - /app/node_modules
    command: sh -c "npm start -- $DAYS_ARG"
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development

  test:
    build: .
    volumes:
      - .:/app
      - /app/node_modules
    command: npm test
